name: 'dotcover-report'
description: 'Reports dotCover output.'
inputs:
  name:
    description: "The name of the check run."
    required: true
    default: 'Test Coverage'
  path:
    description: "The path where the test coverage output has been produced."
    required: true
    default: ''
  version:
    description: "The client version."
    required: false
    default: '0.0.0-preview.0'
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
