name: 'dotcover-report'
description: 'Reports dotCover output.'
inputs:
  name:
    description: "The name of the check run."
    required: true
  path:
    description: "The path of the test coverage output."
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
